const Characters = {
  KAORU_POSTS: [
    'おはようございます～！今日もええ天気やな～☀️ 一日頑張っていこ！',
    'なんか最近調子ええ気がする！みんなもそうやといいな🌸',
    '今日もここにいるよ～！何かあったら話しかけてな😊',
    'お疲れ様～！ちょっとひと息ついていき～☕',
    '毎日コツコツが大事やって、最近ほんまに思うわ～✨',
    'ちょっと疲れたときはゆっくり深呼吸が一番やで～🌿',
    '今日もみんなのこと、応援してるよ💪',
    '小さいことでも、できたことはちゃんと褒めてあげてな～🌟',
    'なんかいい感じやね！🌸',
  ],

  KASUMI_POSTS: [
    '別に、あなたのことが気になってるわけじゃないんだけど…まぁ、元気でやってるといいわね。',
    '今日も普通の一日。でも悪くはなかった。',
    '…ちゃんと休んでる？まぁ、どうでもいいけど。',
    'たまに空を見上げると、少しだけ落ち着く。それだけ。',
    '頑張りすぎは良くないわ。…まぁ、余計なお世話かもしれないけど。',
    'あなたのこと、見てないわけじゃないから。',
    '…今日も無事に過ごせたならそれでいい。',
    '静かな夜って、嫌いじゃない。',
  ],

  KAORU_REPLIES: [
    '読んだよ～！ええな～✨',
    'めっちゃわかる！！',
    'すごいやん！！応援してるで🌸',
    'それ、すごく大事なことやと思う',
    'なんか元気もらえたわ～！ありがとう😊',
    '一緒に頑張ろ～！！',
    'やったね！！おめでとう🎉',
    'うわ～すごい！！見てて楽しい～！',
    'ほんまにお疲れ様やで💪',
    'がんばってるの、ちゃんと見えてるよ～！',
    'なんかいい感じやね！🌸',
    'これすこ🌸',
  ],

  KASUMI_REPLIES: [
    '…まぁ、良かったんじゃない。',
    'ちゃんと見てたわよ。',
    '別に、悪くないと思う。',
    '…頑張ってるのは知ってるから。',
    'それで正解だと思う。余計なこと言わないけど。',
    '…読んだ。それだけ。',
    'また見に来るわ。気が向いたら、だけど。',
    '悪くない。',
    '…あなたらしくていいと思う。',
    'まぁ、見てるから。',
  ],

  PSEUDO_REPLIERS: [
    { name: 'みずき', handle: '@mizuki_life' },
    { name: 'はるか', handle: '@haruka_days' },
    { name: 'ゆうと', handle: '@yuuto_sketch' },
    { name: 'あおい', handle: '@aoi_note' },
    { name: 'たくみ', handle: '@takumi_words' },
    { name: 'なな', handle: '@nana_gentle' },
    { name: 'りく', handle: '@riku_free' },
    { name: 'こころ', handle: '@kokoro_here' },
    { name: 'そら', handle: '@sora_cloud' },
    { name: 'いつき', handle: '@itsuki_slow' },
    { name: 'ひな', handle: '@hina_smile' },
    { name: 'けんと', handle: '@kento_notes' },
  ],

  PSEUDO_REPLIES: [
    'これ好きです',
    'わかります',
    'めっちゃ良い',
    '進捗すごいです',
    '見てて楽しい',
    'いいなあ',
    'なんか元気もらいました',
    'ほんとこれ',
    '素敵です',
    'こういうの好き',
    'お疲れ様です！',
    'すごいです',
    '共感しかない',
    'また見に来ます',
    'いつも楽しみにしてます',
    'なんかいいな～',
    '安心した',
  ],

  rand(arr) { return arr[Math.floor(Math.random() * arr.length)]; },
  getRandomKaoruReply()    { return this.rand(this.KAORU_REPLIES); },
  getRandomKasumiReply()   { return this.rand(this.KASUMI_REPLIES); },
  getRandomKaoruPost()     { return this.rand(this.KAORU_POSTS); },
  getRandomKasumiPost()    { return this.rand(this.KASUMI_POSTS); },
  getRandomPseudoReplier() { return this.rand(this.PSEUDO_REPLIERS); },
  getRandomPseudoReply()   { return this.rand(this.PSEUDO_REPLIES); }
};
